// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: internal/agent/a2a/proto/a2a/v1/a2a.proto

package a2av1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentCardRequest) Reset() {
	*x = GetAgentCardRequest{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentCardRequest) ProtoMessage() {}

func (x *GetAgentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentCardRequest.ProtoReflect.Descriptor instead.
func (*GetAgentCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{0}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CreateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{3}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubscribeTaskEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTaskEventsRequest) Reset() {
	*x = SubscribeTaskEventsRequest{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTaskEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTaskEventsRequest) ProtoMessage() {}

func (x *SubscribeTaskEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTaskEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTaskEventsRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeTaskEventsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// AgentCard 描述 Agent 的能力、技能和端点信息。
type AgentCard struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Protocol        string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities    *AgentCapabilities     `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Endpoints       *AgentEndpoints        `protobuf:"bytes,6,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	SecuritySchemes []*SecurityScheme      `protobuf:"bytes,7,rep,name=security_schemes,json=securitySchemes,proto3" json:"security_schemes,omitempty"`
	Skills          []*AgentSkill          `protobuf:"bytes,8,rep,name=skills,proto3" json:"skills,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{5}
}

func (x *AgentCard) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AgentCard) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCard) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentCard) GetEndpoints() *AgentEndpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *AgentCard) GetSecuritySchemes() []*SecurityScheme {
	if x != nil {
		return x.SecuritySchemes
	}
	return nil
}

func (x *AgentCard) GetSkills() []*AgentSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentCard) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AgentCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputModes    []string               `protobuf:"bytes,1,rep,name=input_modes,json=inputModes,proto3" json:"input_modes,omitempty"`
	OutputModes   []string               `protobuf:"bytes,2,rep,name=output_modes,json=outputModes,proto3" json:"output_modes,omitempty"`
	Streaming     bool                   `protobuf:"varint,3,opt,name=streaming,proto3" json:"streaming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{6}
}

func (x *AgentCapabilities) GetInputModes() []string {
	if x != nil {
		return x.InputModes
	}
	return nil
}

func (x *AgentCapabilities) GetOutputModes() []string {
	if x != nil {
		return x.OutputModes
	}
	return nil
}

func (x *AgentCapabilities) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

type AgentEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	TaskSend      string                 `protobuf:"bytes,2,opt,name=task_send,json=taskSend,proto3" json:"task_send,omitempty"`
	TaskGet       string                 `protobuf:"bytes,3,opt,name=task_get,json=taskGet,proto3" json:"task_get,omitempty"`
	TaskCancel    string                 `protobuf:"bytes,4,opt,name=task_cancel,json=taskCancel,proto3" json:"task_cancel,omitempty"`
	TaskSubscribe string                 `protobuf:"bytes,5,opt,name=task_subscribe,json=taskSubscribe,proto3" json:"task_subscribe,omitempty"`
	AgentCardUrl  string                 `protobuf:"bytes,6,opt,name=agent_card_url,json=agentCardUrl,proto3" json:"agent_card_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEndpoints) Reset() {
	*x = AgentEndpoints{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEndpoints) ProtoMessage() {}

func (x *AgentEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEndpoints.ProtoReflect.Descriptor instead.
func (*AgentEndpoints) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{7}
}

func (x *AgentEndpoints) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AgentEndpoints) GetTaskSend() string {
	if x != nil {
		return x.TaskSend
	}
	return ""
}

func (x *AgentEndpoints) GetTaskGet() string {
	if x != nil {
		return x.TaskGet
	}
	return ""
}

func (x *AgentEndpoints) GetTaskCancel() string {
	if x != nil {
		return x.TaskCancel
	}
	return ""
}

func (x *AgentEndpoints) GetTaskSubscribe() string {
	if x != nil {
		return x.TaskSubscribe
	}
	return ""
}

func (x *AgentEndpoints) GetAgentCardUrl() string {
	if x != nil {
		return x.AgentCardUrl
	}
	return ""
}

type SecurityScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	In            string                 `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityScheme) Reset() {
	*x = SecurityScheme{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityScheme) ProtoMessage() {}

func (x *SecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityScheme.ProtoReflect.Descriptor instead.
func (*SecurityScheme) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{8}
}

func (x *SecurityScheme) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *SecurityScheme) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *SecurityScheme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityScheme) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type AgentSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InputModes    []string               `protobuf:"bytes,4,rep,name=input_modes,json=inputModes,proto3" json:"input_modes,omitempty"`
	OutputModes   []string               `protobuf:"bytes,5,rep,name=output_modes,json=outputModes,proto3" json:"output_modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSkill) Reset() {
	*x = AgentSkill{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSkill) ProtoMessage() {}

func (x *AgentSkill) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSkill.ProtoReflect.Descriptor instead.
func (*AgentSkill) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{9}
}

func (x *AgentSkill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSkill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentSkill) GetInputModes() []string {
	if x != nil {
		return x.InputModes
	}
	return nil
}

func (x *AgentSkill) GetOutputModes() []string {
	if x != nil {
		return x.OutputModes
	}
	return nil
}

// Task 表示一个 A2A 任务。
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Message       *Message               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status        *TaskStatus            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,6,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{10}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Task) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Task) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Task) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Task) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StreamMessage *Message               `protobuf:"bytes,3,opt,name=stream_message,json=streamMessage,proto3" json:"stream_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{11}
}

func (x *TaskStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskStatus) GetStreamMessage() *Message {
	if x != nil {
		return x.StreamMessage
	}
	return nil
}

// Message 是 A2A 协议消息。
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Parts         []*Part                `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{12}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

// Part 表示消息内容片段，可以是文本、文件或结构化数据。
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Part_Text
	//	*Part_File
	//	*Part_Data
	Content       isPart_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{13}
}

func (x *Part) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Part) GetContent() isPart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Part) GetText() *TextPart {
	if x != nil {
		if x, ok := x.Content.(*Part_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Part) GetFile() *FilePart {
	if x != nil {
		if x, ok := x.Content.(*Part_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Part) GetData() *DataPart {
	if x != nil {
		if x, ok := x.Content.(*Part_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPart_Content interface {
	isPart_Content()
}

type Part_Text struct {
	Text *TextPart `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type Part_File struct {
	File *FilePart `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

type Part_Data struct {
	Data *DataPart `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*Part_Text) isPart_Content() {}

func (*Part_File) isPart_Content() {}

func (*Part_Data) isPart_Content() {}

type TextPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPart) Reset() {
	*x = TextPart{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPart) ProtoMessage() {}

func (x *TextPart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPart.ProtoReflect.Descriptor instead.
func (*TextPart) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{14}
}

func (x *TextPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FilePart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*FilePart_FileBytes
	//	*FilePart_FileUri
	Source        isFilePart_Source `protobuf_oneof:"source"`
	Mimetype      string            `protobuf:"bytes,3,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Filename      string            `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{15}
}

func (x *FilePart) GetSource() isFilePart_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FilePart) GetFileBytes() *FileWithBytes {
	if x != nil {
		if x, ok := x.Source.(*FilePart_FileBytes); ok {
			return x.FileBytes
		}
	}
	return nil
}

func (x *FilePart) GetFileUri() *FileWithURI {
	if x != nil {
		if x, ok := x.Source.(*FilePart_FileUri); ok {
			return x.FileUri
		}
	}
	return nil
}

func (x *FilePart) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *FilePart) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type isFilePart_Source interface {
	isFilePart_Source()
}

type FilePart_FileBytes struct {
	FileBytes *FileWithBytes `protobuf:"bytes,1,opt,name=file_bytes,json=fileBytes,proto3,oneof"`
}

type FilePart_FileUri struct {
	FileUri *FileWithURI `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3,oneof"`
}

func (*FilePart_FileBytes) isFilePart_Source() {}

func (*FilePart_FileUri) isFilePart_Source() {}

type FileWithBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWithBytes) Reset() {
	*x = FileWithBytes{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWithBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWithBytes) ProtoMessage() {}

func (x *FileWithBytes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWithBytes.ProtoReflect.Descriptor instead.
func (*FileWithBytes) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{16}
}

func (x *FileWithBytes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileWithBytes) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileWithBytes) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type FileWithURI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWithURI) Reset() {
	*x = FileWithURI{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWithURI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWithURI) ProtoMessage() {}

func (x *FileWithURI) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWithURI.ProtoReflect.Descriptor instead.
func (*FileWithURI) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{17}
}

func (x *FileWithURI) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *FileWithURI) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type DataPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPart) Reset() {
	*x = DataPart{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPart) ProtoMessage() {}

func (x *DataPart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPart.ProtoReflect.Descriptor instead.
func (*DataPart) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{18}
}

func (x *DataPart) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Artifact 是任务产物。
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Mimetype      string                 `protobuf:"bytes,2,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Uri           string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{19}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Artifact) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Artifact) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// TaskEvent 是任务事件流中的事件。
type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Message       *Message               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Artifact      *Artifact              `protobuf:"bytes,6,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP(), []int{20}
}

func (x *TaskEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TaskEvent) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *TaskEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_agent_a2a_proto_a2a_v1_a2a_proto protoreflect.FileDescriptor

const file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDesc = "" +
	"\n" +
	")internal/agent/a2a/proto/a2a/v1/a2a.proto\x12\x06a2a.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x13GetAgentCardRequest\"v\n" +
	"\x11CreateTaskRequest\x12)\n" +
	"\amessage\x18\x01 \x01(\v2\x0f.a2a.v1.MessageR\amessage\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x1aSubscribeTaskEventsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd6\x03\n" +
	"\tAgentCard\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12=\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x19.a2a.v1.AgentCapabilitiesR\fcapabilities\x124\n" +
	"\tendpoints\x18\x06 \x01(\v2\x16.a2a.v1.AgentEndpointsR\tendpoints\x12A\n" +
	"\x10security_schemes\x18\a \x03(\v2\x16.a2a.v1.SecuritySchemeR\x0fsecuritySchemes\x12*\n" +
	"\x06skills\x18\b \x03(\v2\x12.a2a.v1.AgentSkillR\x06skills\x12;\n" +
	"\bmetadata\x18\t \x03(\v2\x1f.a2a.v1.AgentCard.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x11AgentCapabilities\x12\x1f\n" +
	"\vinput_modes\x18\x01 \x03(\tR\n" +
	"inputModes\x12!\n" +
	"\foutput_modes\x18\x02 \x03(\tR\voutputModes\x12\x1c\n" +
	"\tstreaming\x18\x03 \x01(\bR\tstreaming\"\xd1\x01\n" +
	"\x0eAgentEndpoints\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x1b\n" +
	"\ttask_send\x18\x02 \x01(\tR\btaskSend\x12\x19\n" +
	"\btask_get\x18\x03 \x01(\tR\ataskGet\x12\x1f\n" +
	"\vtask_cancel\x18\x04 \x01(\tR\n" +
	"taskCancel\x12%\n" +
	"\x0etask_subscribe\x18\x05 \x01(\tR\rtaskSubscribe\x12$\n" +
	"\x0eagent_card_url\x18\x06 \x01(\tR\fagentCardUrl\"d\n" +
	"\x0eSecurityScheme\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x0e\n" +
	"\x02in\x18\x02 \x01(\tR\x02in\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"\x96\x01\n" +
	"\n" +
	"AgentSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vinput_modes\x18\x04 \x03(\tR\n" +
	"inputModes\x12!\n" +
	"\foutput_modes\x18\x05 \x03(\tR\voutputModes\"\x83\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12)\n" +
	"\amessage\x18\x04 \x01(\v2\x0f.a2a.v1.MessageR\amessage\x12*\n" +
	"\x06status\x18\x05 \x01(\v2\x12.a2a.v1.TaskStatusR\x06status\x12.\n" +
	"\tartifacts\x18\x06 \x03(\v2\x10.a2a.v1.ArtifactR\tartifacts\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x7f\n" +
	"\n" +
	"TaskStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x126\n" +
	"\x0estream_message\x18\x03 \x01(\v2\x0f.a2a.v1.MessageR\rstreamMessage\"}\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\"\n" +
	"\x05parts\x18\x02 \x03(\v2\f.a2a.v1.PartR\x05parts\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"\x9d\x01\n" +
	"\x04Part\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12&\n" +
	"\x04text\x18\x02 \x01(\v2\x10.a2a.v1.TextPartH\x00R\x04text\x12&\n" +
	"\x04file\x18\x03 \x01(\v2\x10.a2a.v1.FilePartH\x00R\x04file\x12&\n" +
	"\x04data\x18\x04 \x01(\v2\x10.a2a.v1.DataPartH\x00R\x04dataB\t\n" +
	"\acontent\"\x1e\n" +
	"\bTextPart\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xb6\x01\n" +
	"\bFilePart\x126\n" +
	"\n" +
	"file_bytes\x18\x01 \x01(\v2\x15.a2a.v1.FileWithBytesH\x00R\tfileBytes\x120\n" +
	"\bfile_uri\x18\x02 \x01(\v2\x13.a2a.v1.FileWithURIH\x00R\afileUri\x12\x1a\n" +
	"\bmimetype\x18\x03 \x01(\tR\bmimetype\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilenameB\b\n" +
	"\x06source\"V\n" +
	"\rFileWithBytes\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\fR\x05bytes\"<\n" +
	"\vFileWithURI\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\x1e\n" +
	"\bDataPart\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xaa\x01\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1a\n" +
	"\bmimetype\x18\x02 \x01(\tR\bmimetype\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\fR\x05bytes\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf7\x01\n" +
	"\tTaskEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12)\n" +
	"\amessage\x18\x05 \x01(\v2\x0f.a2a.v1.MessageR\amessage\x12,\n" +
	"\bartifact\x18\x06 \x01(\v2\x10.a2a.v1.ArtifactR\bartifact\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error2\xbb\x02\n" +
	"\n" +
	"A2AService\x12>\n" +
	"\fGetAgentCard\x12\x1b.a2a.v1.GetAgentCardRequest\x1a\x11.a2a.v1.AgentCard\x125\n" +
	"\n" +
	"CreateTask\x12\x19.a2a.v1.CreateTaskRequest\x1a\f.a2a.v1.Task\x12/\n" +
	"\aGetTask\x12\x16.a2a.v1.GetTaskRequest\x1a\f.a2a.v1.Task\x125\n" +
	"\n" +
	"CancelTask\x12\x19.a2a.v1.CancelTaskRequest\x1a\f.a2a.v1.Task\x12N\n" +
	"\x13SubscribeTaskEvents\x12\".a2a.v1.SubscribeTaskEventsRequest\x1a\x11.a2a.v1.TaskEvent0\x01B]Z[github.com/Gleamseekers/AgentPrimordia/agentprimordia/internal/agent/a2a/proto/a2a/v1;a2av1b\x06proto3"

var (
	file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescOnce sync.Once
	file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescData []byte
)

func file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescGZIP() []byte {
	file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescOnce.Do(func() {
		file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDesc), len(file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDesc)))
	})
	return file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDescData
}

var file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_agent_a2a_proto_a2a_v1_a2a_proto_goTypes = []any{
	(*GetAgentCardRequest)(nil),        // 0: a2a.v1.GetAgentCardRequest
	(*CreateTaskRequest)(nil),          // 1: a2a.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),             // 2: a2a.v1.GetTaskRequest
	(*CancelTaskRequest)(nil),          // 3: a2a.v1.CancelTaskRequest
	(*SubscribeTaskEventsRequest)(nil), // 4: a2a.v1.SubscribeTaskEventsRequest
	(*AgentCard)(nil),                  // 5: a2a.v1.AgentCard
	(*AgentCapabilities)(nil),          // 6: a2a.v1.AgentCapabilities
	(*AgentEndpoints)(nil),             // 7: a2a.v1.AgentEndpoints
	(*SecurityScheme)(nil),             // 8: a2a.v1.SecurityScheme
	(*AgentSkill)(nil),                 // 9: a2a.v1.AgentSkill
	(*Task)(nil),                       // 10: a2a.v1.Task
	(*TaskStatus)(nil),                 // 11: a2a.v1.TaskStatus
	(*Message)(nil),                    // 12: a2a.v1.Message
	(*Part)(nil),                       // 13: a2a.v1.Part
	(*TextPart)(nil),                   // 14: a2a.v1.TextPart
	(*FilePart)(nil),                   // 15: a2a.v1.FilePart
	(*FileWithBytes)(nil),              // 16: a2a.v1.FileWithBytes
	(*FileWithURI)(nil),                // 17: a2a.v1.FileWithURI
	(*DataPart)(nil),                   // 18: a2a.v1.DataPart
	(*Artifact)(nil),                   // 19: a2a.v1.Artifact
	(*TaskEvent)(nil),                  // 20: a2a.v1.TaskEvent
	nil,                                // 21: a2a.v1.AgentCard.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
}
var file_internal_agent_a2a_proto_a2a_v1_a2a_proto_depIdxs = []int32{
	12, // 0: a2a.v1.CreateTaskRequest.message:type_name -> a2a.v1.Message
	6,  // 1: a2a.v1.AgentCard.capabilities:type_name -> a2a.v1.AgentCapabilities
	7,  // 2: a2a.v1.AgentCard.endpoints:type_name -> a2a.v1.AgentEndpoints
	8,  // 3: a2a.v1.AgentCard.security_schemes:type_name -> a2a.v1.SecurityScheme
	9,  // 4: a2a.v1.AgentCard.skills:type_name -> a2a.v1.AgentSkill
	21, // 5: a2a.v1.AgentCard.metadata:type_name -> a2a.v1.AgentCard.MetadataEntry
	12, // 6: a2a.v1.Task.message:type_name -> a2a.v1.Message
	11, // 7: a2a.v1.Task.status:type_name -> a2a.v1.TaskStatus
	19, // 8: a2a.v1.Task.artifacts:type_name -> a2a.v1.Artifact
	22, // 9: a2a.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	22, // 10: a2a.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	22, // 11: a2a.v1.Task.expires_at:type_name -> google.protobuf.Timestamp
	12, // 12: a2a.v1.TaskStatus.stream_message:type_name -> a2a.v1.Message
	13, // 13: a2a.v1.Message.parts:type_name -> a2a.v1.Part
	14, // 14: a2a.v1.Part.text:type_name -> a2a.v1.TextPart
	15, // 15: a2a.v1.Part.file:type_name -> a2a.v1.FilePart
	18, // 16: a2a.v1.Part.data:type_name -> a2a.v1.DataPart
	16, // 17: a2a.v1.FilePart.file_bytes:type_name -> a2a.v1.FileWithBytes
	17, // 18: a2a.v1.FilePart.file_uri:type_name -> a2a.v1.FileWithURI
	22, // 19: a2a.v1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	22, // 20: a2a.v1.TaskEvent.timestamp:type_name -> google.protobuf.Timestamp
	12, // 21: a2a.v1.TaskEvent.message:type_name -> a2a.v1.Message
	19, // 22: a2a.v1.TaskEvent.artifact:type_name -> a2a.v1.Artifact
	0,  // 23: a2a.v1.A2AService.GetAgentCard:input_type -> a2a.v1.GetAgentCardRequest
	1,  // 24: a2a.v1.A2AService.CreateTask:input_type -> a2a.v1.CreateTaskRequest
	2,  // 25: a2a.v1.A2AService.GetTask:input_type -> a2a.v1.GetTaskRequest
	3,  // 26: a2a.v1.A2AService.CancelTask:input_type -> a2a.v1.CancelTaskRequest
	4,  // 27: a2a.v1.A2AService.SubscribeTaskEvents:input_type -> a2a.v1.SubscribeTaskEventsRequest
	5,  // 28: a2a.v1.A2AService.GetAgentCard:output_type -> a2a.v1.AgentCard
	10, // 29: a2a.v1.A2AService.CreateTask:output_type -> a2a.v1.Task
	10, // 30: a2a.v1.A2AService.GetTask:output_type -> a2a.v1.Task
	10, // 31: a2a.v1.A2AService.CancelTask:output_type -> a2a.v1.Task
	20, // 32: a2a.v1.A2AService.SubscribeTaskEvents:output_type -> a2a.v1.TaskEvent
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_internal_agent_a2a_proto_a2a_v1_a2a_proto_init() }
func file_internal_agent_a2a_proto_a2a_v1_a2a_proto_init() {
	if File_internal_agent_a2a_proto_a2a_v1_a2a_proto != nil {
		return
	}
	file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[13].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_File)(nil),
		(*Part_Data)(nil),
	}
	file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes[15].OneofWrappers = []any{
		(*FilePart_FileBytes)(nil),
		(*FilePart_FileUri)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDesc), len(file_internal_agent_a2a_proto_a2a_v1_a2a_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agent_a2a_proto_a2a_v1_a2a_proto_goTypes,
		DependencyIndexes: file_internal_agent_a2a_proto_a2a_v1_a2a_proto_depIdxs,
		MessageInfos:      file_internal_agent_a2a_proto_a2a_v1_a2a_proto_msgTypes,
	}.Build()
	File_internal_agent_a2a_proto_a2a_v1_a2a_proto = out.File
	file_internal_agent_a2a_proto_a2a_v1_a2a_proto_goTypes = nil
	file_internal_agent_a2a_proto_a2a_v1_a2a_proto_depIdxs = nil
}
